package com.wg.demo.mapper;

import com.wg.demo.pojo.Category;
import com.wg.demo.pojo.CategoryExample;
import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbg.generated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbg.generated
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_
     *
     * @mbg.generated
     */
    List<Category> selectByExample(CategoryExample example);
}